package sme.ejb.db.model;
// Generated May 16, 2019 10:28:33 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historial generated by hbm2java
 */
@Entity
@Table(name = "historial", catalog = "smedb")
public class Historial implements java.io.Serializable {

	private Integer idhistorial;
	private Nodo nodo;
	private Date fecha;
	private boolean cfePresente;
	private boolean upsPresente;
	private Date fechaNotificacion;

	public Historial() {
	}

	public Historial(Nodo nodo, Date fecha, boolean cfePresente, boolean upsPresente, Date fechaNotificacion) {
		this.nodo = nodo;
		this.fecha = fecha;
		this.cfePresente = cfePresente;
		this.upsPresente = upsPresente;
		this.fechaNotificacion = fechaNotificacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idhistorial", unique = true, nullable = false)
	public Integer getIdhistorial() {
		return this.idhistorial;
	}

	public void setIdhistorial(Integer idhistorial) {
		this.idhistorial = idhistorial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idnodo", nullable = false)
	public Nodo getNodo() {
		return this.nodo;
	}

	public void setNodo(Nodo nodo) {
		this.nodo = nodo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "cfe_presente", nullable = false)
	public boolean isCfePresente() {
		return this.cfePresente;
	}

	public void setCfePresente(boolean cfePresente) {
		this.cfePresente = cfePresente;
	}

	@Column(name = "ups_presente", nullable = false)
	public boolean isUpsPresente() {
		return this.upsPresente;
	}

	public void setUpsPresente(boolean upsPresente) {
		this.upsPresente = upsPresente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_notificacion", nullable = false, length = 19)
	public Date getFechaNotificacion() {
		return this.fechaNotificacion;
	}

	public void setFechaNotificacion(Date fechaNotificacion) {
		this.fechaNotificacion = fechaNotificacion;
	}

}
