package sme.ejb.db.model;
// Generated May 16, 2019 10:28:33 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * ModemLocal generated by hbm2java
 */
@Entity
@Table(name = "modem_local", catalog = "smedb")
public class ModemLocal implements java.io.Serializable {

	private Integer idmodemLocal;
	private int version;
	private String numero;
	private String puerto;
	private int baudrate;
	private int databits;
	private String parity;
	private int stopbits;
	private boolean activo;
	private boolean monitoreoActivo;

	public ModemLocal() {
	}

	public ModemLocal(String puerto, int baudrate, int databits, String parity, int stopbits, boolean activo,
			boolean monitoreoActivo) {
		this.puerto = puerto;
		this.baudrate = baudrate;
		this.databits = databits;
		this.parity = parity;
		this.stopbits = stopbits;
		this.activo = activo;
		this.monitoreoActivo = monitoreoActivo;
	}

	public ModemLocal(String numero, String puerto, int baudrate, int databits, String parity, int stopbits,
			boolean activo, boolean monitoreoActivo) {
		this.numero = numero;
		this.puerto = puerto;
		this.baudrate = baudrate;
		this.databits = databits;
		this.parity = parity;
		this.stopbits = stopbits;
		this.activo = activo;
		this.monitoreoActivo = monitoreoActivo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idmodem_local", unique = true, nullable = false)
	public Integer getIdmodemLocal() {
		return this.idmodemLocal;
	}

	public void setIdmodemLocal(Integer idmodemLocal) {
		this.idmodemLocal = idmodemLocal;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "numero", length = 20)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "puerto", nullable = false, length = 45)
	public String getPuerto() {
		return this.puerto;
	}

	public void setPuerto(String puerto) {
		this.puerto = puerto;
	}

	@Column(name = "baudrate", nullable = false)
	public int getBaudrate() {
		return this.baudrate;
	}

	public void setBaudrate(int baudrate) {
		this.baudrate = baudrate;
	}

	@Column(name = "databits", nullable = false)
	public int getDatabits() {
		return this.databits;
	}

	public void setDatabits(int databits) {
		this.databits = databits;
	}

	@Column(name = "parity", nullable = false, length = 15)
	public String getParity() {
		return this.parity;
	}

	public void setParity(String parity) {
		this.parity = parity;
	}

	@Column(name = "stopbits", nullable = false)
	public int getStopbits() {
		return this.stopbits;
	}

	public void setStopbits(int stopbits) {
		this.stopbits = stopbits;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "monitoreo_activo", nullable = false)
	public boolean isMonitoreoActivo() {
		return this.monitoreoActivo;
	}

	public void setMonitoreoActivo(boolean monitoreoActivo) {
		this.monitoreoActivo = monitoreoActivo;
	}

}
